### ISSUE TITLE
Authorization with the JS SDK not working - multiple issues

### ISSUE THREAD

**Issue by mcclymont** [konfig-dev/splitit-web-sdks#15]
Attempting to use the JS SDK
https://www.npmjs.com/package/splitit-web-typescript-sdk/v/3.3.6

 like so:

```
const splitit = new Splitit({
  basePath: 'https://web-api-v3.sandbox.splitit.com',
  oauthClientId: env.SPLITIT_OAUTH_CLIENT_ID,
  oauthClientSecret: env.SPLITIT_OAUTH_CLIENT_SECRET,
});


splitit.installmentplan
    .get({installmentPlanNumber: '0FE1JR94UY4CMU4RDTCR', xSplititIdempotencyKey: '1234', xSplititTouchPoint: ''})
    .then((res) => console.log(res.data.Amount) );
```

I get a 401 error.
After some debugging of the JS SDK, I found that it is trying to obtain an oAuth access token but the URL it is requesting is blank string.

Setting this property on the Splitit constructor fixed this problem. It would be good if the documentation could be updated to include mention of oauthTokenUrl in the quick start section.
```
  oauthTokenUrl: 'https://id.sandbox.splitit.com/connect/token',
```

But then there was an additional problem, where it was setting the Authorization header to the value "Bearer Bearer"

This is because of the code here https://github.com/konfig-dev/splitit-web-sdks/blob/57f6f8e47f3350079f591de7feec352c97bb42bd/typescript/common.ts#L125
It matches on the `token_type: 'Bearer'` instead of the `access_token: '65ffc2504914427aa683edd7e4a722bb-1'` value and thus the auth header becomes 'Bearer Bearer'

When I fixed this issue in the JS SDK, it seemed to work fine for the first request to SplitIt API, but the subsequent request would fail in some code for parsing a JWT, where I decided to stop debugging

**Comment by dphuang2** [comment]
@mcclymont thanks for reporting this bug! I will take a look and publish is fix when ready.

**Comment by mcclymont** [comment]
Oh also, the documentation and TS types say to set the xSplititTouchPoint, but I don't know what this value is for

**Comment by eddiechayes** [comment]
Hi @mcclymont, both of these issues have been fixed with the new release of the typescript SDK today, version 3.3.10. Please try it out!

- The token url now defaults to https://id.production.splitit.com/connect/token if not provided
- the bug causing the header value to be "Bearer Bearer" has been fixed

**Comment by mcclymont** [comment]
Thanks @eddiechayes.

In the issue I describe 3 problems. The first 2 are fixed, but the 3rd one remains:

> When I fixed this issue in the JS SDK, it seemed to work fine for the first request to SplitIt API, but the subsequent request would fail in some code for parsing a JWT, where I decided to stop debugging

To reproduce this, you need to make a second request through the SDK so it uses the cached/remembered access_token

I'm surprised that the library is trying to parse the oauth access_token as a JWT

```
InvalidTokenError: Invalid token specified: missing part #2
    at jwtDecode (/Users/chris/repos/nowcircular/monorepo/services/subscriptions/node_modules/.pnpm/jwt-decode@4.0.0/node_modules/jwt-decode/build/cjs/index.js:46:15)
    at /Users/chris/repos/nowcircular/monorepo/services/subscriptions/node_modules/.pnpm/splitit-web-typescript-sdk@3.3.10/node_modules/splitit-web-typescript-sdk/dist/common.js:152:61
    at Generator.next (<anonymous>)
    at fulfilled (/Users/chris/repos/nowcircular/monorepo/services/subscriptions/node_modules/.pnpm/splitit-web-typescript-sdk@3.3.10/node_modules/splitit-web-typescript-sdk/dist/common.js:17:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[ERROR] 11:32:06 InvalidTokenError: Invalid token specified: missing part #2
```

**Comment by eddiechayes** [comment]
@mcclymont Thanks for clarifying. I'll take a look and get back to you shortly.

**Comment by eddiechayes** [comment]
@mcclymont Please try the most recent version of the SDK (4.0.1), I have fixed this issue.
